version: '3.8'

services:
  bolt-ai-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-production
      args:
        - NODE_ENV=production
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - WRANGLER_SEND_METRICS=false
      - RUNNING_IN_DOCKER=true
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bolt-ai.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.bolt-ai.tls=true"
      - "traefik.http.routers.bolt-ai.tls.certresolver=letsencrypt"
      - "traefik.http.services.bolt-ai.loadbalancer.server.port=5173"
    networks:
      - bolt-network

networks:
  bolt-network:
    driver: bridge